/**
 * Single source of truth. Edit names, date, venue, story, timeline,
 * maps, RSVP, music, and every AR/EN string here.
 */
const CONFIG = {
  weddingDate: "2026-10-15T20:00:00",
  durationHours: 4,
  mapsUrl: "https://maps.app.goo.gl/ViYL5JB8U7FouXW1A",
  rsvpEndpoint: "/api/rsvp",
  music: "LwL24fGL_YY",
  calendarFile: "ahmed-toka.ics",

  i18n: {
    ar: {
      pageTitle: "فرح أحمد وتقي",
      tap: "اضغط للفتح",
      openAria: "فتح الدعوة",
      langAria: "التبديل إلى الإنجليزية",
      muteAria: "تشغيل الموسيقى أو إيقافها",
      scrollAria: "تشغيل التمرير التلقائي أو إيقافه",
      calAria: "إضافة الموعد إلى التقويم",
      mapAria: "فتح الموقع",
      skip: "تخطي إلى الدعوة",
      groom: "أحمد",
      bride: "تقي",
      and: "و",
      weddingOf: "الفرح",
      dateNumeric: "١٥ · ١٠ · ٢٠٢٦",
      storyKicker: "قصتنا",
      storyTitle: "كُتبت في السماء",
      storyLead: "بعض القصص تبدأ بلحظة.",
      storyBody: "وقصتنا بدأت بشعور صار إلى الأبد.",
      dateKicker: "احفظوا الموعد",
      dayNum: "١٥",
      monthName: "أكتوبر",
      yearNum: "٢٠٢٦",
      dateNote: "من الثامنة مساءً حتى منتصف الليل.",
      countKicker: "العد التنازلي",
      countLead: "حتى نقول",
      countWord: "قبلنا",
      countNote: "كل ثانية تقربنا من الأبد.",
      d: "يوم",
      h: "ساعة",
      m: "دقيقة",
      s: "ثانية",
      timeKicker: "برنامج الحفل",
      timeNote: "ليلة تُحفظ، وقصة تُروى إلى الأبد.",
      timeline: [
        { time: "٨:٠٠ م", title: "بداية الحفل" },
        { time: "١٠:٠٠ م", title: "العشاء" },
        { time: "١٢:٠٠ ص", title: "نهاية الحفل" }
      ],
      venueKicker: "المكان",
      venueName: "القاعة الماسية بدار المشاة",
      venueCity: "من ٨ مساءً حتى ١٢ منتصف الليل",
      venueNote: "مكان جميل لليلة لا تُنسى.",
      map: "افتح الموقع",
      venueClose: "نتطلع للاحتفال معكم بهذه الليلة الجميلة.",
      rsvpTitle: "تأكيد الحضور",
      name: "الاسم",
      namePh: "اكتبوا الاسم هنا",
      attending: "هل ستشاركونا يومنا؟",
      yes: "نعم",
      no: "لا",
      message: "اكتبوا تهنئتكم",
      messagePh: "اكتبوا تهنئتكم هنا",
      send: "إرسال",
      sending: "جاري الإرسال…",
      thanksKicker: "شكراً لكم",
      thanksNote: "شكراً لكونكم جزءاً من يومنا.",
      coupleLine: "أحمد و تقي",
      thanksDate: "١٥ · ١٠ · ٢٠٢٦",
      thanks: "شكراً، تم إرسال التأكيد",
      nameMissing: "من فضلكم اكتبوا الاسم ثم أرسلوا مرة أخرى.",
      error: "حدث خطأ، حاولوا مرة أخرى.",
      calendarSummary: "فرح أحمد وتقي",
      addCal: "أضف إلى التقويم"
    },
    en: {
      pageTitle: "Ahmed & Toka",
      tap: "Tap to open",
      openAria: "Open invitation",
      langAria: "Switch to Arabic",
      muteAria: "Play or pause music",
      scrollAria: "Play or pause auto-scroll",
      calAria: "Add the date to your calendar",
      mapAria: "Open location",
      skip: "Skip to invitation",
      groom: "Ahmed",
      bride: "Toka",
      and: "&",
      weddingOf: "The Wedding",
      dateNumeric: "15.10.2026",
      storyKicker: "Our Story",
      storyTitle: "Written in the Stars",
      storyLead: "Some stories begin with a moment.",
      storyBody: "Ours began with a feeling that became forever.",
      dateKicker: "Save the Date",
      dayNum: "15",
      monthName: "October",
      yearNum: "2026",
      dateNote: "From 8 PM until midnight.",
      countKicker: "Countdown",
      countLead: "Until We Say",
      countWord: "I Do",
      countNote: "Every second brings us closer to forever.",
      d: "Days",
      h: "Hours",
      m: "Minutes",
      s: "Seconds",
      timeKicker: "Wedding Timeline",
      timeNote: "A night to remember, a story to treasure forever.",
      timeline: [
        { time: "8:00 PM", title: "The evening begins" },
        { time: "10:00 PM", title: "Dinner" },
        { time: "12:00 AM", title: "End of the night" }
      ],
      venueKicker: "Location",
      venueName: "The Diamond Hall, Dar Al-Mashah",
      venueCity: "8:00 PM – 12:00 AM",
      venueNote: "A beautiful place for our unforgettable night.",
      map: "Open Location",
      venueClose: "We can’t wait to celebrate this beautiful night with you.",
      rsvpTitle: "RSVP",
      name: "Your name",
      namePh: "Type your name",
      attending: "Will you be attending our day?",
      yes: "Yes",
      no: "No",
      message: "Write your congratulations",
      messagePh: "Write a few words",
      send: "Send",
      sending: "Sending…",
      thanksKicker: "Thank You",
      thanksNote: "Thank you for being part of our special day.",
      coupleLine: "Ahmed & Toka",
      thanksDate: "15 · 10 · 2026",
      thanks: "Thank you",
      nameMissing: "Please write your name, then send again.",
      error: "Something went wrong, please try again.",
      calendarSummary: "Ahmed & Toka — The Wedding",
      addCal: "Add to Calendar"
    }
  }
};
